plugins {
    id "com.android.application"
}

android {
    namespace "com.mekari.mobile_hardening_xposed_probe"
    compileSdk 34

    defaultConfig {
        applicationId "com.mekari.mobile_hardening_xposed_probe"
        minSdk 23
        targetSdk 32
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    compileOnly "de.robv.android.xposed:api:82"
}
