apply plugin: "com.android.application"
apply plugin: "kotlin-android"

android {
    namespace = "com.mekari.mobile_hardening_kit.sample"
    compileSdk = 34

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId = "com.mekari.mobile_hardening_kit.sample"
        minSdk = 23
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"
    }
}

dependencies {
    // In an app outside this repo, use the Maven coordinates from the README instead:
    // implementation "com.mekari.mobile_hardening_kit:mobile-hardening-kit:0.1.0"
    implementation project(":core")
}
